PROGRAM = gpio_mirror

PROJECT_ROOT = $(shell pwd)/../../../../..

COMMON_DIR = $(PROJECT_ROOT)/sw/ibex/common

C_INCLUDES = -I$(PROJECT_ROOT)/uvm/sw

# All other source files are include in the main.c (single-source build approach)
C_SOURCES = main.c 	
	
include $(COMMON_DIR)/common.mk
