#ifndef SYS_ERR_H
#define SYS_ERR_H

#include <stdint.h>

// TODO: proper name, make an enum
#define SYS_ERR_STRING_INVALID_HEX_ADDR_FORMAT 800
#define SYS_ERR_MEM_INVALID_ADDR 900

typedef enum {
    SYSTEM_ERROR_NONE = 0,

    SYSTEM_ERROR_CLI_INVALID_ARGUMENT_COUNT = 100,
    SYSTEM_ERROR_CLI_UNKNOWN_COMMAND = 101,

    SYSTEM_ERROR_CLI_CMD_NOT_FOUND = 100,
    SYSTEM_ERROR_CLI_CMD_ECHO_INVALID_ARG_COUNT = 101,
    SYSTEM_ERROR_CLI_CMD_MEM_INVALID_ARG_COUNT = 102,
    SYSTEM_ERROR_CLI_CMD_MEM_UNKNOWN_SUB_COMMAND = 103,
    SYSTEM_ERROR_CLI_CMD_MEM_READ_INVALID_ARG_COUNT = 104,

    SYSTEM_ERROR_STRING_INVALID_HEX_ADDR_FORMAT = 200,

    SYSTEM_ERROR_MEM_INVALID_ADDR = 300,
} system_error_enum;

typedef uint32_t system_error_t;

void system_error_print(system_error_t error);

#endif
