#ifndef SYS_ERR_H
#define SYS_ERR_H

#include <stdint.h>

// TODO: proper name, make an enum
#define SYS_ERR_STRING_INVALID_HEX_ADDR_FORMAT 800
#define SYS_ERR_MEM_INVALID_ADDR 900

typedef enum {
    SYSTEM_ERROR_NONE = 0,

    SYSTEM_ERROR_CLI_INVALID_ARGUMENT_COUNT = 100,
    SYSTEM_ERROR_CLI_UNKNOWN_COMMAND = 101,
    SYSTEM_ERROR_CLI_CMD_NOT_FOUND = 100,
    SYSTEM_ERROR_CLI_CMD_ECHO_INVALID_ARG_COUNT = 101,
    SYSTEM_ERROR_CLI_CMD_MEM_INVALID_ARG_COUNT = 102,
    SYSTEM_ERROR_CLI_CMD_MEM_UNKNOWN_SUB_COMMAND = 103,
    SYSTEM_ERROR_CLI_CMD_MEM_READ_INVALID_ARG_COUNT = 104,
    SYSTEM_ERROR_CLI_CMD_MEM_INVALID_ADDR = 105,
    SYSTEM_ERROR_CLI_CMD_MEM_WORD_COUNT_EXCEED_MEMORY = 106,
    SYSTEM_ERROR_CLI_CMD_MEM_SUBCMD_NOT_FOUND = 107,
    SYSTEM_ERROR_CLI_CMD_MEM_READ_INVALID_ADDR_HEX_FORMAT = 108,
    SYSTEM_ERROR_CLI_CMD_MEM_READ_INVALID_ADDR = 109,
    SYSTEM_ERROR_CLI_CMD_MEM_WRITE_INVALID_ARG_COUNT = 110,
    SYSTEM_ERROR_CLI_CMD_MEM_WRITE_INVALID_ADDR_HEX_COUNT = 111,
    SYSTEM_ERROR_CLI_CMD_MEM_WRITE_INVALID_ADDR = 112,
    SYSTEM_ERROR_CLI_CMD_MEM_WRITE_INVALID_VALUE_HEX_FORMAT = 113,
    SYSTEM_ERROR_CLI_CMD_MEM_DUMP_INVALID_ARG_COUNT = 114,
    SYSTEM_ERROR_CLI_CMD_MEM_DUMP_INVALID_ADDR_HEX_FORMAT = 115,
    SYSTEM_ERROR_CLI_CMD_MEM_DUMP_INVALID_ADDR = 116,
    SYSTEM_ERROR_CLI_CMD_MEM_DUMP_INVALID_WORD_COUNT_HEX_FORMAT = 117,
    SYSTEM_ERROR_CLI_CMD_MEM_DUMP_WORD_COUNT_EXCEED_MEMORY = 118,
    SYSTEM_ERROR_CLI_CMD_MEM_DUMP_START_ADDR_EXCEEDS_END_ADDR = 119,
    SYSTEM_ERROR_CLI_CMD_MEM_CHECKSUM_INVALID_ARG_COUNT = 120,
    SYSTEM_ERROR_CLI_CMD_MEM_CHECKSUM_INVALID_ADDR_HEX_FORMAT = 121,
    SYSTEM_ERROR_CLI_CMD_MEM_CHECKSUM_INVALID_ADDR = 122,
    SYSTEM_ERROR_CLI_CMD_MEM_CHECKSUM_INVALID_WORD_COUNT_HEX_FORMAT = 123,
    SYSTEM_ERROR_CLI_CMD_MEM_CHECKSUM_WORD_COUNT_EXCEED_MEMORY = 124,
    SYSTEM_ERROR_CLI_CMD_MEM_CHECKSUM_START_ADDR_EXCEEDS_END_ADDR = 125,
    // lowercase letters only 0xffa80011, not 0xFFFF or 0Xfff
    SYSTEM_ERROR_STRING_INVALID_HEX_FORMAT = 200,
} system_error_enum;

typedef uint32_t system_error_t;

void system_error_print(system_error_t error);

#endif
