#ifndef SYS_MEM_H
#define SYS_MEM_H

#define SYS_MEM_IMEM_BASE_ADDR 0x80000000UL
#define SYS_MEM_DMEM_BASE_ADDR 0x90000000UL

#define SYS_MEM_IMEM_SIZE 8192UL
#define SYS_MEM_DMEM_SIZE 4096UL

#define SYS_MEM_IMEM_ADDR_VALID(a) \
    ((a) >= SYS_MEM_IMEM_BASE_ADDR && \
     (a) <= (SYS_MEM_IMEM_BASE_ADDR + SYS_MEM_IMEM_SIZE - 4))

#define SYS_MEM_DMEM_ADDR_VALID(a) \
    ((a) >= SYS_MEM_DMEM_BASE_ADDR && \
     (a) <= (SYS_MEM_DMEM_BASE_ADDR + SYS_MEM_DMEM_SIZE - 4))

#define SYS_MEM_ADDR_VALID(a) \
    (SYS_MEM_IMEM_ADDR_VALID(a) || SYS_MEM_DMEM_ADDR_VALID(a))

#endif
