services:
  verilator:
    build:
      context: .
      dockerfile: sim/verilator/dockerfile
      args:
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}

    # uniquely tag the image per-user to avoid shared-server conflicts
    image: mlab-mcu-uvm-${USER:-latest}:latest

    hostname: mlab
    stdin_open: true
    tty: true

    environment:
      # stop host machine and docker from fighting over compiled python files
      - PYTHONDONTWRITEBYTECODE=1

    # workspace mount to local: MLAB_MCU or MLAB_MCU_edu root project repo
    volumes:
      - ..:/home/mcu
