FROM rockylinux@sha256:e8a49c5403b687db05d4d67333fa45808fbe74f36e683cec7abb1f7d0f2338c6

RUN dnf install -y epel-release dnf-plugins-core && \
    dnf config-manager --set-enabled powertools || true

RUN dnf install -y \
        gcc gcc-c++ make patch automake autoconf bison flex \
        gcc-riscv64-linux-gnu \
        findutils which \
        python3.12 python3.12-devel python3.12-pip \
        libX11 libXext libXft libXrender \
        glibc.i686 glibc-devel.i686 && \
    dnf clean all

RUN alternatives --set python3 /usr/bin/python3.12

WORKDIR /home/mcu/uvm

ENV PYTHONDONTWRITEBYTECODE=1

CMD ["/bin/bash"]
