PROGRAM = uart_heartbeat

PROJECT_ROOT = $(shell pwd)/../../../../..

COMMON_DIR = $(PROJECT_ROOT)/sw/ibex/common

C_INCLUDES = -I$(PROJECT_ROOT)/uvm/sw

C_SOURCES = main.c

include $(COMMON_DIR)/common.mk
