PROGRAM = gpio_heartbeat

PROJECT_ROOT = $(shell pwd)/../../../../..

COMMON_DIR = $(PROJECT_ROOT)/sw/ibex/common

C_SOURCES = core/src/main.c

C_INCLUDES = -Icore/inc

include $(COMMON_DIR)/common.mk
